name: 'Test Reports'

on:
  workflow_run:
    workflows: [ 'Build Module' ]
    types: [ completed ]

jobs:
  report:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tests: [dotnet-results, pester-results]
    runs-on: unbuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: ${{ matrix.tests }}-${{ matrix.os }}
          name: ${{ matrix.tests }}-${{ matrix.os }}
          path: '*.xml'
          reporter: 'dotnet-trx'